# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ÷o
email: d.linggar@icloud.com
description: > # this means to ignore newlines until "baseurl:"
  <b>Dennys Linggar</b> is a <em>Web Developer by profession, an automotive enthusiast by passion</em>. He's currently a postgraduate student at The University of Queensland and a <em>freelance web developer</em>.


baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dennyspatera.com" # the base hostname & protocol for your site
twitter_username: dennyslinggar
github_username:  ColdDrip

# Build settings
markdown: kramdown
